Improve to use multi-arch images when building services
dockersamples/example-voting-app pull request #250
Opened 2022-10-04 15:06 UTC by glours

I updated redis, postgres images and all the base images used in Docker files
Also rename `docker-compose-*` files to `compose-*` to follow the Compose specification.
And used `--platform=BUILDPLATFORM` to be sure the user platform will be use when building the stack

2022-10-05 08:02 UTC, thaJeztah requested changes

2022-10-05 08:02 UTC, thaJeztah commented on result/Dockerfile
>  RUN apt-get update \
Erm... looks like there's more to fix; this doesn't take multi-arch into account, and always downloads x86 (also looks like it's not statically linked?); https://github.com/krallin/tini/releases/tag/v0.19.0

```bash
docker build -t foo -<<'EOF'
FROM scratch AS tini
ARG TINI_VERSION=v0.19.0
ADD --chmod=0755 https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
EOF

docker run --rm foo /tini --version
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

And doesn't work on alpine 😞 

```bash
ldd /tini
	/lib/ld-linux-aarch64.so.1 (0xffffb203e000)
	libc.so.6 => /lib/ld-linux-aarch64.so.1 (0xffffb203e000)
Error relocating /tini: __fprintf_chk: symbol not found
```

This looks to work though;

```dockerfile
FROM scratch AS tini
ARG TINI_VERSION=v0.19.0
ARG TARGETARCH
ADD --chmod=0755 https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${TARGETARCH} /tini

FROM debian:bullseye-slim
COPY --from=tini /tini /tini
```

```bash
docker run --rm foo /tini --version
tini version 0.19.0 - git.de40ad0
```


```bash
docker run --rm foo /tini --version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
tini version 0.19.0 - git.de40ad0
```

2022-12-16 21:56 UTC, mikesir87 commented
Hey all! Thanks for the PR @glours and the conversation. Seeing there are unresolved conversations, a lot of updates in a single PR, and the PR is in conflict, we're going to go ahead and close this one. But, there are several pieces to this PR we _do_ want to bring forward in future PRs.

2022-12-16 21:56 UTC, closed without merging

2022-12-16 22:18 UTC, BretFisher commented
Thanks, @glours and @thaJeztah for this effort. We've resolved some of the issues addressed in this PR over the last few weeks and are creating tasking to ensure we include the rest of @glours ideas.